#############################################################################
# Makefile for building: SMS_Notifier
# Generated by qmake (2.01a) (Qt 4.7.4) on: Wed Mar 21 15:26:02 2012
# Project:  SMS_Notifier.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe -spec c:\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf SMS_Notifier.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/sys"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/app"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/app"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/app/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/app/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/moc"  -I"C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/ui"  -I"C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier"  -I"C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/rcc" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/SMS_Notifier.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/SMS_Notifier.pro
	$(QMAKE) "C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/SMS_Notifier.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc: 
	$(QMAKE) "C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/SMS_Notifier.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
release: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c armv5_urel -c armv6_urel
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c armv5_urel -c armv6_urel
freeze-release: bld.inf
	$(SBS) freeze -c armv5_urel -c armv6_urel

debug-winscw: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-rvct4.0: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v5.udeb.rvct4_0
clean-debug-armv5-rvct4.0: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.rvct4_0
freeze-debug-armv5-rvct4.0: bld.inf
	$(SBS) freeze -c arm.v5.udeb.rvct4_0
release-armv5-rvct4.0: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v5.urel.rvct4_0
clean-release-armv5-rvct4.0: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.rvct4_0
freeze-release-armv5-rvct4.0: bld.inf
	$(SBS) freeze -c arm.v5.urel.rvct4_0
debug-armv5-gcce4.4.1: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-rvct4.0: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v6.udeb.rvct4_0
clean-debug-armv6-rvct4.0: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.rvct4_0
freeze-debug-armv6-rvct4.0: bld.inf
	$(SBS) freeze -c arm.v6.udeb.rvct4_0
release-armv6-rvct4.0: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v6.urel.rvct4_0
clean-release-armv6-rvct4.0: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.rvct4_0
freeze-release-armv6-rvct4.0: bld.inf
	$(SBS) freeze -c arm.v6.urel.rvct4_0
debug-armv6-gcce4.4.1: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/release/winscw/udeb/SMS_Notifier.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis SMS_Notifier.sis SMS_Notifier.exe $(QT_RUN_OPTIONS)

SMS_Notifier_template.pkg: C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/SMS_Notifier.pro
	$(MAKE) -f $(MAKEFILE) qmake

SMS_Notifier_installer.pkg: C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/SMS_Notifier.pro
	$(MAKE) -f $(MAKEFILE) qmake

SMS_Notifier_stub.pkg: C:/Users/vdr/Dropbox/Vijay_Private/SMS_Notifier/SMS_Notifier.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: SMS_Notifier_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) SMS_Notifier_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: SMS_Notifier_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o SMS_Notifier_template.pkg $(QT_SIS_TARGET)

SMS_Notifier.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: SMS_Notifier_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: SMS_Notifier_installer.pkg
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) SMS_Notifier_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: SMS_Notifier_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: SMS_Notifier_installer.pkg
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o SMS_Notifier_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: SMS_Notifier_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) SMS_Notifier_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call SMS_Notifier.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_mainwindow.cpp
moc\moc_mainwindow.cpp: cnotifier.h \
		mainwindow.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\mainwindow.h -o c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\moc\moc_mainwindow.cpp

compiler_rcc_make_all: rcc\qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_images.cpp
rcc\qrc_images.cpp: images.qrc \
		test.png
	c:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\rcc.exe -name images c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\images.qrc -o c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\rcc\qrc_images.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui\ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui\ui_mainwindow.h
ui\ui_mainwindow.h: mainwindow.ui
	c:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\uic.exe c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\mainwindow.ui -o c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\ui\ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

dodistclean:
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_template.pkg" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_template.pkg"
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_stub.pkg" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_stub.pkg"
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_installer.pkg" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_installer.pkg"
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\Makefile" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\Makefile"
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_exe.mmp" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_exe.mmp"
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_reg.rss" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier_reg.rss"
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.rss" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.rss"
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\SMS_Notifier.loc"
	-@ if EXIST "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\bld.inf" $(DEL_FILE)  "c:\Users\vdr\Dropbox\Vijay_Private\SMS_Notifier\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel


